### ISSUE TITLE
Example project does not work in IE11

### ISSUE THREAD

**Issue by MrNightingale** [fullcalendar/fullcalendar-vue#143]
Do you support IE11? Since I face with next issue 
`Object doesn't support property or method "undefined"`

**Version**: @fullcalendar/vue": 4.3.1

![image](https://user-images.githubusercontent.com/9369682/104719009-7c48e500-5734-11eb-887b-8ccfadc99150.png)

**Comment by acerix** [comment]
IE11 is supported, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by MrNightingale** [comment]
@acerix How can I reproduce it if codesandbox, codepen and etc. doesn't support IE11? Also, your example vue code is not working IE11 too. Both v4 and v5.

I've deployed my code to netlify `https://fullcalendar-vue-demo.netlify.app/`
My code `https://github.com/MrNightingale/fullcalendar-example-projects/tree/master/vue`

**Comment by acerix** [comment]
I'll test the Vue example project in IE11 tomorrow when I have access to Windows.   

If you can make a demo in codepen showing the issue, you can change the view to "debug" which allows it to run in IE11.

**Comment by acerix** [comment]
I can confirm the demo project doesn't work in IE11, though I get a different error:

![Screenshot_2021-01-26_12-10-31](https://user-images.githubusercontent.com/379534/105902417-9f08b280-5fec-11eb-8e31-18aa6f2335ab.png)

I tried this in package.json but still getting errors so I'm not sure what is missing,  may need a babel plugin.  

```
  "browserslist": [
    "IE 11"
  ],
```

**Comment by MrNightingale** [comment]
Yes, error isn't the same but I think we should start with fix for the initial project.

**Comment by MrNightingale** [comment]
What is the current status of issue?

**Comment by arshaw** [comment]
@MrNightingale , I looked at your netlify link. The error is occuring on the Webpack preamble, not the FullCalendar-Vue code. Webpack's preamble has an ES6 arrow function that is not compatible with IE11. The solution is to configure Webpack to be more compatible:

https://github.com/fullcalendar/fullcalendar-example-projects/commit/89968dd4626570f3b116924ee2b9529b3d55239b

The example project running in IE11:

![Screen Shot 2021-06-02 at 2 55 12 PM](https://user-images.githubusercontent.com/56520/120536859-979a5100-c3b2-11eb-8d0d-d44e142c28f5.png)
